[env:4d_systems_esp32s3_gen4_r8n16]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/Abdurraziq/ZMPT101B-arduino
    robtillaart/ACS712@^0.3.9
    bblanchon/ArduinoJson@^6.21.0
    milesburton/DallasTemperature@^3.11.0
    paulstoffregen/OneWire@^2.3.7
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
    marcoschwartz/LiquidCrystal_I2C@^1.1.4